export const USER_FORM_SERVICE = 'USER_FORM_SERVICE';

export const USER_SIGN_UP_SAGA = 'USER_SIGN_UP_SAGA';

export const GET_USER_ADMIN = 'GET_USER_ADMIN';
export const GET_USER_ADMIN_SAGA = 'GET_USER_ADMIN_SAGA';

export const DELETE_USER_ADMIN_SAGA = 'DELETE_USER_ADMIN_SAGA';
export const OPEN_FORM_EDIT_USER_ADMIN = 'OPEN_FORM_EDIT_USER_ADMIN';
export const SET_SUBMIT_EDIT_USER_ADMIN = 'SET_SUBMIT_EDIT_USER_ADMIN';
export const UPDATE_USER_ADMIN_SAGA = 'UPDATE_USER_ADMIN_SAGA';
export const UPDATE_USER_ADMIN = 'UPDATE_USER_ADMIN';
export const EDIT_USER_ADMIN_MODAL = 'EDIT_USER_ADMIN_MODAL';
export const SEARCH_USER_ADMIN = 'SEARCH_USER_ADMIN';
export const GET_USER_SEARCH_ADMIN_SAGA = 'GET_USER_SEARCH_ADMIN_SAGA';
export const GET_USER_SEARCH_ADMIN = 'GET_USER_SEARCH_ADMIN';
